Add authorization
mentality-prj/mentality-web pull request #5
Opened 2024-10-29 09:56 UTC by petelkavictor

2024-10-29 20:38 UTC, TarasGez requested changes
Please, add examples of secret keys that you use to the file .env.example in this format
```
AUTH_GOOGLE_ID={CLIENT_ID}
AUTH_GOOGLE_SECRET={CLIENT_SECRET}

AUTH_GITHUB_ID={CLIENT_ID}
AUTH_GITHUB_SECRET={CLIENT_SECRET}
```

2024-10-29 20:38 UTC, TarasGez commented on components/GoogleButton.tsx
Can we use SSR? like this:
```
import { signIn } from '@/auth'
import { Button } from '@/components'

function Auth() {
  const login = async () => {
    'use server'
    await signIn('google', { redirectTo: '/profile' })
  }
  return (
    <form action={login}>
      <h1>Login page</h1>
      <Button type="submit">Signin with Google</Button>
    </form>
  )
}
export default Auth
```

2024-10-29 20:38 UTC, TarasGez commented on configs/auth.ts
We can use it without secret keys:
```
import NextAuth, { NextAuthConfig } from 'next-auth'
import GitHub from 'next-auth/providers/github'
import Google from 'next-auth/providers/google'

export const authOptions: NextAuthConfig = {
  providers: [Google, GitHub],
}

export const { handlers, signIn, signOut, auth } = NextAuth(authOptions)
```
Just add correct names for keys to .env.local:
(https://authjs.dev/getting-started/authentication/oauth)
AUTH_GOOGLE_ID={CLIENT_ID}
AUTH_GOOGLE_SECRET={CLIENT_SECRET}

2024-10-29 20:38 UTC, TarasGez commented on components/ProfileButton.tsx
> +  const session = useSession()
we can use SSR ```const session = await auth()```

2024-10-30 08:10 UTC, closed without merging

2024-10-30 08:18 UTC, petelkavictor commented
used NextAuth.js (v4 -  [https://next-auth.js.org](url) ) instead of Auth.js (NextAuth.js v5 - [https://authjs.dev](url) ). Therefore, I close the PR to make authorization on the correct version